### ISSUE TITLE
Approximate solution to dR/dt

### ISSUE THREAD

**Issue by maxbiostat** [maxbiostat/R0_uncertainty#20]
https://math.unm.edu/~sulsky/mathcamp/ApplyData.pdf. Have to cross-check with the [notes](https://github.com/maxbiostat/R0_uncertainty/blob/master/notes/SIRmodels.pdf).

**Comment by maxbiostat** [comment]
![image](https://user-images.githubusercontent.com/2875083/60044604-1c45a600-9699-11e9-8f7e-478570c48922.png)
This is from Murray, 2002

**Comment by fccoelho** [comment]
I had already sent you this from Eric Rensahw's book (2011).

**Comment by maxbiostat** [comment]
I know. The problem is that the solution you sent does not work. Thus I posted this here so we can compare both solutions and see if the algebra matches. Note that 'rho = 1/R0 = gamma/beta'. It is possible that the solution might not work well then R/rho is large.
